[package]
name = "rlox"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysexits = "0.4.1"
phf = { version = "0.11", features = ["macros"] }
